name = "MemoryEfficientIOs"
uuid = "f3d7dbc7-e5fd-42ba-983a-13510bd2b112"
authors = ["cihga39871 <jiacheng_chuan@outlook.com>"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
StringViews = "^1.0"
Reexport = "^1.0"
julia = "1.0"
